### ISSUE TITLE
Where is the grep version?

### ISSUE THREAD

**Issue by thenoobtester** [benhoyt/countwords#110]
Hi,

I can't find the grep. Could you please share a link? I saw it arrived first in this article (it's in French):

https://programmation.developpez.com/actu/313618/Les-langages-Python-et-AWK-sont-juste-recommandables-pour-leur-rapidite-Go-et-Rust-pour-leur-rapidite-et-leur-fiabilite-selon-Ben-Hoyt-Ingenieur-logiciel-chez-Canonical/

Thank you

**Comment by benhoyt** [comment]
The `grep` and `wc` "versions" were just there to indicate a baseline of "how fast you can read or tokenize a file" type of thing, they don't actually solve the problem of counting word frequencies. See the [command lines used here](https://github.com/benhoyt/countwords/blob/0ad4306cfa0b34cba26d7c229ac022de2bf9a48b/benchmark.py#L23).

Interesting to see my article referenced in a French publication, thanks!
