### ISSUE TITLE
Improve notes on how to profile in golang

### ISSUE THREAD

**Issue by dazzag24** [benhoyt/countwords#13]
Hi,
Thanks for the great article.  I'm new-ish to golang to was really interested in the comment about using pprof.  However I struggled to get this working with your instructions because although you stated what code was to be added to the main() you didn't mention how to import the profiling functions.

Took me a while to mind the correct way of doing this (as I was initially sent down a wrong path by an alternative net/http/pprof import) is to import `runtime/pprof`

```
package main

import (
        "bufio"
        "fmt"
        "os"
        "sort"
        "strings"
        "runtime/pprof"
)

func main() {

        f, err := os.Create("cpuprofile")
        if err != nil {
                fmt.Fprintf(os.Stderr, "could not create CPU profile: %v\n", err)
                os.Exit(1)
        }
        if err := pprof.StartCPUProfile(f); err != nil {
                fmt.Fprintf(os.Stderr, "could not start CPU profile: %v\n", err)
                os.Exit(1)
        }
        defer pprof.StopCPUProfile()

        scanner := bufio.NewScanner(os.Stdin)
        scanner.Split(bufio.ScanWords)
        counts := make(map[string]int)
        for scanner.Scan() {
                word := strings.ToLower(scanner.Text())
                counts[word]++
        }
        if err := scanner.Err(); err != nil {
                fmt.Fprintln(os.Stderr, err)
                os.Exit(1)
        }

        var ordered []Count
<snip>
```

Thanks

Darren

**Comment by benhoyt** [comment]
Ah, good point -- I've clarified a little bit in the article: https://github.com/benhoyt/benhoyt.github.com/commit/a0fd29b9af10ea4958c745a72713a58656252b3a
