### ISSUE TITLE
optimized.py is wrong if the last line doesn't end with a newline

### ISSUE THREAD

**Issue by Voultapher** [benhoyt/countwords#28]
This input `the fox\nfox` should print: `fox 2\nthe 1\n` yet it prints `the 1\nfox 1\n`.

Goes to show that chunks are tricky.

**Comment by benhoyt** [comment]
Thanks, good find! Can you please submit a PR with the fix?

**Comment by Voultapher** [comment]
Can do. When talking about optimizations I feel we as an industry are too reckless, correctness should nearly always trump performance. The code we write is no longer some fun thought experiment some uni students talk about, code is seeping into every aspect of our lives and has an ever increasing impact on real peoples lives. And a lot of that has to do with our software engineering culture. One small step you could make with your article, would be to mention you got the original version wrong and emphasize more strongly the recklessness of chasing performance without rigorous testing.

**Comment by benhoyt** [comment]
It's a fair point in general. However, in this article I wasn't aiming for well-tested versions, and I'm sure there are other edge cases I'm missing. In real life if I had to optimize something like this I'd have a suite of tests: short lines, long lines, ending LF, no ending LF, big buffer, small buffer, etc. Your point stands, though -- correctness should trump performance.
