### ISSUE TITLE
C# version

### ISSUE THREAD

**Issue by jftuga** [benhoyt/countwords#3]
I have a C# version here: [freq.cs](https://github.com/jftuga/universe/blob/master/freq.cs)

With Visual Studio 2019, you can compile to `.exe` by running:

    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe freq.cs

Note that this version [sorts the output](https://github.com/jftuga/universe/blob/master/freq.cs#L43) which you may not want in your benchmark version.  On line 45, you could change `tbl_sorted` to `tbl` to output unsorted results (after commenting out line 43).

**EDIT:** I just remembered this operates on a line-by-line basis and not word-by-word.

**Comment by benhoyt** [comment]
Thanks for that. Yeah, we need to tokenize / parse the line into words. Also, it only needs to handle stdin and not files, so you could make that simplification. If you make those two changes, I'd link to it under Other Languages for the C# version.

I love how simple and clean the sorting is in C#.

Out of interest, how did you find out about this repository? From my comp.lang.forth posting?

**Comment by jftuga** [comment]
I will work on this.

I found this because @BurntSushi cloned your repo - I guess to write the rust version.  I was looking at what else he has done, other than `ripgrep`.

**Comment by benhoyt** [comment]
Nice, and no problems -- was just curious!

Thanks for the C# version. Ideally it'd run on Linux, so I can benchmark it against the other language versions on the same machine. I guess the best way to do that is Mono? https://www.mono-project.com/

**Comment by jftuga** [comment]
I created a PR.  I would agree that Mono would be the best way to test.  I wrote this program using Windows 10 and Visual Studio 2019.  It's pretty simple, so I would assume Mono would not have any problems running it.

**Comment by benhoyt** [comment]
Excellent, thanks. I'll close this issue in favour of your PR.

**Comment by jbergens** [comment]
I have not checked the code yet but .NET on Linux is most often done by using .NET Core or the new .NET 5. Then you can both compile and run on Linux and the program will probably be faster.

**Comment by benhoyt** [comment]
Yeah, I'm now running it with .NET 5 on Linux.
