### ISSUE TITLE
Shell version

### ISSUE THREAD

**Issue by jftuga** [benhoyt/countwords#4]
Depending on how large your file is, you may get better performance by using something like this:

   export LC_ALL=C
   sort -S 8G --parallel=4 -T /mnt/fast_ssd/tmp | uniq -c | sort -n -r -S 8G --parallel=4 -T /mnt/fast_ssd/tmp

This will use up to 8 GB of memory before switching over to using files that are ideally on a fast disk. It will also use multiple threads for sorting.

**Comment by benhoyt** [comment]
Good pointers, thanks. For me, a bigger `-S` sort buffer helped quite a bit (from ~3s to 2s) on the first sort (the second sort is small) but `--parallel` didn't add anything. I'm guessing parallel would help very *super* large inputs. I've updated the benchmark in https://github.com/benhoyt/countwords/commit/40a4406649f94ee6e795148b0f65bf142a0edce0
