### ISSUE TITLE
C version using Judy array

### ISSUE THREAD

**Issue by sjpschutte** [benhoyt/countwords#52]
I have been using the venerable Judy arrays (http://judy.sourceforge.net/) for many years now and was curious to see how it will fare in your test.
I was a bit disappointed to see it being slower than even simple case.
At least it seems to have the best memory usage. ( time -v  report)

I can send you a pull request if you are interested in adding it.

**Comment by benhoyt** [comment]
Thanks for thinking of it, but I probably wouldn't include it seeing it is both slower and probably not more simple (and I've already done both versions for C). Thanks anyway!

**Comment by sjpschutte** [comment]
No worries.

It is actually more simple.

You can have a quick peek here https://github.com/sjpschutte/countwords/blob/master/judytree.c

**Comment by benhoyt** [comment]
Ah, interesting. Boy, that is one terse/funky API with names like JSLF, JSLI, JSLA :-) In any case, given that it's slower and uses a third party library (not libc or POSIX), I'll decline. Thanks though!
