### ISSUE TITLE
.NET environment

### ISSUE THREAD

**Issue by osman-turan** [benhoyt/countwords#60]
I'm using .NET Core 5.0 on macOS. As far as I know, `dotnet build` command generates a `.dll` file and one can invoke the output with `dotnet output.dll`. Do you use something else (like Mono on Linux or something else)? Because in test scripts, it looks like you generate standalone executables and this does not work in my system. Could you verify the following does work for you, please? If so, I'll provide a PR for it.

**Before**
```bash
# from test.sh
echo C# simple
dotnet build ./csharp/simple -c Release
./csharp/simple/bin/Release/net5.0/simple <kjvbible_x10.txt | python3 normalize.py >output.txt
git diff --exit-code output.txt
```

**After**
```bash
# from test.sh
echo C# simple
dotnet build ./csharp/simple -c Release
dotnet ./csharp/simple/bin/Release/net5.0/simple.dll <kjvbible_x10.txt | python3 normalize.py >output.txt
git diff --exit-code output.txt
```

**Comment by erikbozic** [comment]
I'm running on linux and both ways work for me on .NET Core 5. Not sure why osx sdk would behave differently. It's not just permissions is it? :sweat_smile:

**Comment by sfesenko** [comment]
`dotnet build` should produce executable wrapper next to dll assembly

Also, if you run dll assembly "directly", via `dotnet`, you'll have startup penalty (~ 1 sec), that is not good for running benchmarks

**Comment by benhoyt** [comment]
Thanks for testing. Yeah, both ways work for me on .NET on Linux.

**Comment by osman-turan** [comment]
@erikbozic 
> I'm running on linux and both ways work for me on .NET Core 5. Not sure why osx sdk would behave differently. It's not just permissions is it?

Nope. There is only .dll file in the build folder.

@sfesenko
> dotnet build should produce executable wrapper next to dll assembly

This is not true in my case, unfortunately.

> Also, if you run dll assembly "directly", via dotnet, you'll have startup penalty (~ 1 sec), that is not good for running benchmarks

Thanks for the tip!

@benhoyt 

> Thanks for testing. Yeah, both ways work for me on .NET on Linux.

Thanks!
