### ISSUE TITLE
Clarify the criteria for the test set

### ISSUE THREAD

**Issue by wfxr** [benhoyt/countwords#61]
It would be better if the criteria for the test set can be clearly defined.

I looked into some implementations in different languages, and found they made different assumptions for the test set. These assumptions in fact have a very big impact on performance.

For example the simple `php` solution assumes that the input is all ascii encoding (`strtolower`) and no stablity requirment for the sort (`arsort`). At the same time, ~~all of rust's solutions assume~~ the simple rust solution assumes the input is utf-8 encoded and stable sorting is used.

**Comment by BurntSushi** [comment]
> At the same time, All of rust's solutions assume the input is utf-8 encoded and stable sorting is used.

That's not true. Only the simple variant does. None of the others do.

The ASCII assumption is documented in the blog post.

**Comment by BurntSushi** [comment]
I believe sort order is also addressed.

**Comment by wfxr** [comment]
@BurntSushi ops I forget the `optimized` solutions also use ASCII assumption.

**Comment by wfxr** [comment]
I have tried replace `to_lowercase` with `to_ascii_lowercase` will speed up the simple rust solution significantly but not sure should we can make such an assumption. So I opend this issue.

**Comment by BurntSushi** [comment]
> I have tried replace `to_lowercase` with `to_ascii_lowercase` will speed up the simple rust solution significantly but not sure should we can make such an assumption. So I opened this issue.

The point of `simple` is not to optimize it. The point of `simple` is to show a simple idiomatic program that one would write in the given language. It's pretty much exactly the program I would write in Rust if I were given the interview question and they said performance wasn't an important factor.

To that end, programs should use whatever comes natural in their respective environments. In Rust, that's absolutely `to_lowercase`.

**Comment by wfxr** [comment]
@BurntSushi Thank you. I get what you mean. I think we may have focused on two different aspects. IMO, choosing a more appropriate API based on a given input without increasing the code complexity will not have any negative effects. They still `simple` and the only difference is the api name. You are right I will also write the same solution firstly if we don't care the performance. But I don't think that replacing `to_lowercase` with `to_ascii_lowercase` considering the input criteria will change the fact that this is still a **simple** solution. If we pursue the absolute simplicity, maybe there is no need for `try_main` as well? （ I maybe will not think of it in the interview you mentioned above but it's really a good pattern I think )

**Comment by BurntSushi** [comment]
I think the idea is to write a simple version of the program that is in the spirit of the challenge. Since the "spirit of the challenge" is not a precise well specified set of rules, we could argue endlessly about the proper manifestation in the source code. I personally don't care to do that. While I'm not perfect, I think `to_lowercase` is more in line with the spirit of the challenge that `to_ascii_lowercase` is.

**Comment by wfxr** [comment]
I respect your opinion.
