### ISSUE TITLE
python version with pandas, ~0.25 seconds

### ISSUE THREAD

**Issue by apiszcz** [benhoyt/countwords#80]
Great article, another approach for your consideration

```
import time
import pandas as pd

t0=time.time()
data = open(r'kjvbible.txt').read()
data = data.lower().split()
df = pd.DataFrame(data,columns=['word'])
wordfreq = df.value_counts())
print(time.time()-t0)
```

**Comment by benhoyt** [comment]
Nice! However, it's not within the constraints, which says "use only standard libraries" and "don't read the whole file at once".

Additionally, I noticed you're using `kjvbible.txt` and not `kjvbible_x10.txt` like the rest of the benchmarks, so your "0.25 seconds" would probably be 10x that.

Thanks anyway!
