### ISSUE TITLE
node.js in results slower than expected

### ISSUE THREAD

**Issue by carstenschwede** [benhoyt/countwords#99]
I was wondering why you got much slower results for JavaScript than I did while other results (e.g. Python and C++) are very similar (macOS, 2.4GHz i9). Could you check if you have a recent node.js version (>=15) and that startup times for your node.js is not unintentionally delayed (>150ms) because of a node version management setup or something similar?

| Language | Your result | My result |
| --- | --- | --- |
| C++ | 0.28 | 0.29 |
| Python | 1.31 | 1.32 |
| JavaScript | 1.78 | 0.97 |
| JavaScript (nop) | ? | 0.15 |

```
$> hyperfine --warmup 10 -m 10 './optimized-cpp <kjvbible_x10.txt > /dev/null'
Benchmark #1: ./optimized-cpp <kjvbible_x10.txt > /dev/null
  Time (mean ± σ):     285.2 ms ±  13.9 ms    [User: 253.5 ms, System: 30.2 ms]
  Range (min … max):   263.4 ms … 308.7 ms    11 runs
```

```
$> hyperfine --warmup 10 -m 10 'python3 optimized.py <kjvbible_x10.txt > /dev/null'
Benchmark #1: python3 optimized.py <kjvbible_x10.txt > /dev/null
  Time (mean ± σ):      1.315 s ±  0.027 s    [User: 1.241 s, System: 0.106 s]
  Range (min … max):    1.277 s …  1.355 s    10 runs
```

```
$>  hyperfine --warmup 10 -m 10 'node optimized.js <kjvbible_x10.txt > /dev/null'
Benchmark #1: node optimized.js <kjvbible_x10.txt > /dev/null
  Time (mean ± σ):     966.9 ms ±  35.2 ms    [User: 888.4 ms, System: 109.3 ms]
  Range (min … max):   935.0 ms … 1029.6 ms    10 runs
```

```
$> hyperfine --warmup 10 -m 10 'node empty.js <kjvbible_x10.txt > /dev/null'
Benchmark #1: node empty.js <kjvbible_x10.txt > /dev/null
  Time (mean ± σ):     148.6 ms ±   3.9 ms    [User: 81.2 ms, System: 90.1 ms]
  Range (min … max):   141.0 ms … 155.7 ms    19 runs
```

**Comment by benhoyt** [comment]
Hmm, interesting. I did have an old version of Node (v10.19.0, which came with `apt install` on my Ubuntu focal install). I installed v15.12.0 and the startup time is *much* better (~60ms to run empty.js instead of ~400ms -- the latter is a crazy startup time!).

Old version: simple 2.42, optimized 1.78
New version: simple 2.11, optimized 1.15

The rest of the discrepancy is probably because I'm on Linux and have a slower machine (i7).

I'll update the benchmarks shortly.

**Comment by benhoyt** [comment]
Updated. Also added a file that shows exactly which versions I'm using: https://github.com/benhoyt/countwords/blob/master/versions.txt

**Comment by carstenschwede** [comment]
Awesome! Your versions.txt is still showing the 10.19.0 btw. I am still wondering why node.js is >15% slower on your machine  but the Python and C++ are not. Might be platform specific. Could you take another look at https://github.com/benhoyt/countwords/pull/89? `{}` is really not a hash table in JavaScript. I find it reasonable to allow a custom hash table when the language does not explicitly provide one (`Map` and `Object.create(null)` can be used in a 'hash table fashion' but have additional overheads that all actual hash table implementations in other languages do not have)

**Comment by benhoyt** [comment]
Re version 10.19.0: ah, woops, I had a bash alias which was using the correct version in my tests, but not when I ran versions.sh. Updated. Yeah, I'm putting the rest down to being platform-specific issues.

I know it's a bit arbitrary that I can do it in C but not other languages, but I'm on the fence about JavaScript. I'm going to leave as is for now.
